### ISSUE TITLE
docker / docker-compose / plugins

### ISSUE THREAD

**Issue by roscopecoltran** [morucci/repoxplorer#23]
Hey,

Hope u are doing all well !

I was wondering if you have included  a **docker-compose** file and a **Dockerfile**, of course, alpine based ^^, for your interesting [repoxplorer](https://github.com/morucci/repoxplorer) project.

It would help to add some plugins and create an aggregation data api for some advanced search with more advanced faceted searches.

**Examples:**
  - for code search:
      - https://github.com/google/zoekt
      - https://github.com/boyter/searchcode-server
      - https://github.com/boyter/searchcode
  - for user's starred  search
      - trends
      - topics filtering

Ps. Why ? ^^ I am sometimes frustrated by the the basic search functions of github, gitlab and want to re-use a common elasticsearch stack managing my VCS activities.

Cheers,
Richard

**Comment by morucci** [comment]
Hi @roscopecoltran 

Thanks for interest in repoXplorer.

I haven't yet managed to "dockerize" it, I thought about it but that's not an item in my short-term roadmap. I produce a centos7 RPM that should also work on Fedora so I was more thinking about a docker file based on Centos or Fedora :)

Searchcode seems really nice and seems to fit well with the multi-repo capability of repoXplorer so that's sound a good idea to deploy both to get repo stats and code search. Is it based on ElasticSearch ? can't find the info.

Regarding repoXplorer the project will stay focus on (cross)-repository stats faceted by projects, contributors and group/org and I won't provide code search feature. Code is not indexed only commit metadata and maybe I'll just provide a way to search through commit message.

Cheers,
Fabien

**Comment by josephholsten** [comment]
@morucci pretty sure we can close this, or at least split it into smaller changes if you think work remains

**Comment by morucci** [comment]
The simplest way to deploy repoXplorer is based on docker-compose see: https://github.com/morucci/repoxplorer#quickstart---use-the-repoxplorer-docker-container-to-index-a-github-organization

It is not alpine based but centos instead as all python deps are packaged in centos. I suppose with alpine all deps should be fetched from pip so it should work. Feel free to propose a PR, I'll be happy to have container based on Alpine too.
