### ISSUE TITLE
Elasticsearch still 2.4?

### ISSUE THREAD

**Issue by markwalkom** [morucci/repoxplorer#48]
Following on from #28, I ran through the steps in the [1.4.0 tag README](https://github.com/morucci/repoxplorer/tree/1.4.0) but it still looks like it's running Elasticsearch 2.4.X;

```
[root@897d5eaa38ca /]# curl -H "Content-Type: application/json" 0:9200
{
  "name" : "Katrina Luisa van Horne",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "76Wui7i8TVqZJ2Y04wf0rg",
  "version" : {
    "number" : "2.4.6",
    "build_hash" : "5376dca9f70f3abef96a77f4bb22720ace8240fd",
    "build_timestamp" : "2017-07-18T12:17:44Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.4"
  },
  "tagline" : "You Know, for Search"
}
```

Not sure if I am missing something here?

**Comment by morucci** [comment]
Hi,

The morucci/repoxplorer:last container on Docker Hub is still 1.4.0 while EL 6.X support is only on master.
I haven't tagged repoxplorer since 1.4.0.  So what you see in the container is normal.

But I have published a morucci/repoxplorer:master container on the hub (https://hub.docker.com/r/morucci/repoxplorer/tags) and provided the instructions in that just merged commit: https://github.com/morucci/repoxplorer/commit/4d2432e8bb17ab00b785f17f08dbe98b3a48eb8a

There is docker-compose-master.yaml that you should be able to use. It works from my side.

Let me know if you see any issue.

**Comment by markwalkom** [comment]
Ok. looks like am a bit confused with the README pointing to 1.4.0 on a few occasions.
